//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UvaentaInventory.Resources.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Request = new HashSet<Request>();
        }
    
        public string EquipmentSN { get; set; }
        public int EquipmentModelID { get; set; }
        public int CabinetID { get; set; }
        public int EquipmentTypeID { get; set; }
        public int ResponsibleID { get; set; }
        public string EquipmentName { get; set; }
        public Nullable<System.DateTime> DatePurchase { get; set; }
        public int StatusID { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual EquipmentModel EquipmentModel { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Responsible Responsible { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
